# Even Fibonacci numbers
# Problem 2
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
a=1
b=2
x=[1]
y=[2]
z=[1,2]
while a<4000000:
    c=a+b
    print(c)
    d=b+c
    print(d)
    if c<4000000:
        x.append(c)
        z.append(c)
    if d<4000000:
        y.append(d)
        z.append(d)
    a=c
    b=d
print(a,x,y,z)

m=sum(x)
n=sum(y)
print(m,n)

l=[]
for i in z:
    if i%2==0:
        l.append(i)

print(l)
o=sum(l)
print(o)
